---
galaxy_info:
  author: Tychart
  description: My custom collection
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Redhat
      versions:
        - 33
collections:
  - name: my_collection
    version: 1.0.0
